### PR TITLE
Update detective to latest version

### PR DESCRIPTION
**Pull request by toddself**
Detective 2.x uses an old version of Esprima for parsing the files, this
unforunately does not support ES6 syntax (I specifically had problems
with template strings). The latest version of detective uses acorn which
does support template strings correctly.

Also updated the test to work in a later version of browserify as the
output from bundle and the place into which to pass the `debug`
parameter have moved.

(Also hi!)

### CODE REVIEW

**Comment by johnkpaul** [comment]
:+1: 

Thanks @toddself! I really appreciate the PR and that you follow browserify closer than I do. :)

When are you back in NYC? Come visit.

**Comment by toddself** [comment]
Needed to do some client-side debugging during a massive refactor of our front end out of globals & concatenation and this is the best tool for the job!

I'm out Oct 13-16 -- are you going to be at BrooklynJS that week?

**Comment by toddself** [comment]
Oh! Can you do a quick `npm publish` as well :smile:

**Comment by johnkpaul** [comment]
Ah sorry, forgot! `npm publish`'d

:/ I'm going to be out of town during BrooklynJS, but maybe we could get lunch earlier? Will move to twitter.

**Pull request merged**
